plugins {
    id 'java'
}

group = 'sharks'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.microsoft.playwright:playwright:1.41.0'
    testImplementation 'org.testng:testng:7.9.0'
    testImplementation 'org.slf4j:slf4j-simple:2.0.11'

    // Allure залежність для TestNG
    testImplementation 'io.qameta.allure:allure-testng:2.25.0'
}

test {
    useTestNG()

    // Вказуємо систему зберігати Allure-результати в папку build/allure-results
    systemProperty 'allure.results.directory', "$buildDir/allure-results"
}